FROM debian:11

LABEL maintainer="Michael Act < michael.4ct@gmail.com >"

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/* \
    && gosu nobody true
